<?php

/**
 * @file
 * Contains nocurrent_pass.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nocurrent_pass_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.nocurrent_pass':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module makes the "current password" field on the user edit form optional.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a checkbox to disable or enable the Current Password field.
 */
function nocurrent_pass_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {
  // Get configuration.
  $nocurrent_pass_disabled = \Drupal::config('nocurrent_pass.settings')->get('nocurrent_pass_disabled');

  // Reorder fieldset weights.
  $form['anonymous_settings']['#weight'] = -4;
  $form['admin_role']['#weight'] = -3;
  $form['registration_cancellation']['#weight'] = -2;

  // Add "Do not require current password" field and its fieldset.
  $form['nocurrent_pass_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Require Current Password'),
    '#weight' => -1,
  ];
  $form['nocurrent_pass_settings']['nocurrent_pass_disabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Do not require current password'),
    '#description' => t('Check this box to disable the "current password" field on the User Edit form.'),
    '#default_value' => $nocurrent_pass_disabled,
  ];

  // Add submit function which saves the settings into configuration.
  $form['#submit'][] = 'nocurrent_pass_form_user_admin_settings_submit';
}

/**
 * Provides the submit callback for the admin settings form.
 */
function nocurrent_pass_form_user_admin_settings_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('nocurrent_pass.settings');
  $config->set('nocurrent_pass_disabled', (bool) $form_state->getValue('nocurrent_pass_disabled'));
  $config->save();
}

/**
 * Implements hook_form_alter().
 *
 * Remove the current password field from the user form.
 * It works for both(user/%/edit && user/%/change-password routes.
 */
function nocurrent_pass_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'user_form':
    case 'change_pwd_form':
      // Get the module's configuration.
      $config = \Drupal::config('nocurrent_pass.settings');

      // If the Current password is disabled.
      if ($config->get('nocurrent_pass_disabled')) {
        $account = $form_state->getFormObject()->getEntity();

        // If this is not the Superadmin's edit page.
        if (!empty($account) && $account->id() != 1) {

          // Turn off Current password field's validation.
          $form_state->set('user_pass_reset', 1);

          // Hide the Current password fields.
          $form['account']['current_pass']['#access'] = FALSE;
        }
      }
      break;

  }
}
