<?php

/**
 * @file
 * Contains install and update functions for Commerce PayPal.
 */

/**
 * Install the PayPal Checkout payment method type.
 */
function commerce_paypal_update_8101() {
  $entity_type = \Drupal::entityTypeManager()->getDefinition('commerce_payment_method');
  \Drupal::service('entity.bundle_plugin_installer')->installBundles($entity_type, ['commerce_paypal']);
}

/**
 * Install the PayPal Checkout payment method type.
 */
function commerce_paypal_update_8102() {
  $entity_type = \Drupal::entityTypeManager()->getDefinition('commerce_payment_method');
  \Drupal::service('entity.bundle_plugin_installer')->installBundles($entity_type, ['commerce_paypal']);
}

/**
 * Move the credit messaging settings to a different config object.
 */
function commerce_paypal_update_8103() {
  $config_factory = \Drupal::configFactory();
  $legacy_config = $config_factory->getEditable('commerce_paypal.settings');
  $client_id = $legacy_config->get('commerce_paypal.credit_messaging_client_id');
  if ($client_id) {
    $config = $config_factory->getEditable('commerce_paypal.credit_messaging_settings');
    $config
      ->set('client_id', $client_id)
      ->set('add_to_cart', $legacy_config->get('commerce_paypal.credit_messaging_add_to_cart'))
      ->save();
    $legacy_config->delete();
  }
}

/**
 * Disables credit card icon settings on existing payment gateways.
 */
function commerce_paypal_update_8104() {
  $payment_gateways = \Drupal::entityTypeManager()
    ->getStorage('commerce_payment_gateway')
    ->loadMultiple();

  foreach ($payment_gateways as $payment_gateway) {
    if ($payment_gateway->getPluginId() !== 'paypal_checkout') {
      continue;
    }
    $configuration = $payment_gateway->getPluginConfiguration();
    $configuration['enable_credit_card_icons'] = FALSE;
    $payment_gateway->setPluginConfiguration($configuration);
    $payment_gateway->save();
  }
}

/**
 * Install the new fastlane payment method type fields.
 */
function commerce_paypal_update_8105() {
  $entity_type = \Drupal::entityTypeManager()
    ->getDefinition('commerce_payment_method');
  \Drupal::service('entity.bundle_plugin_installer')
    ->installBundles($entity_type, ['commerce_paypal']);
}

/**
 * Add Fastlane pane to the correct step on checkout flow.
 */
function commerce_paypal_update_9301(): void {
  /** @var \Drupal\commerce_checkout\Entity\CheckoutFlowInterface[] $checkout_flows */
  $checkout_flows = \Drupal::entityTypeManager()
    ->getStorage('commerce_checkout_flow')
    ->loadMultiple();

  // Add/remove Fastlane pane based on used plugin in checkout flow.
  foreach ($checkout_flows as $checkout_flow) {
    $configuration = $checkout_flow->get('configuration');
    if ($checkout_flow->getPluginId() === 'paypal_fastlane') {
      if (!isset($configuration['panes']['paypal_fastlane_contact_information'])) {
        $configuration['panes']['paypal_fastlane_contact_information'] = [
          'step' => 'order_information',
          'weight' => 2,
        ];
      }
    }
    else {
      unset($configuration['panes']['paypal_fastlane_contact_information']);
    }
    $checkout_flow->set('configuration', $configuration)->save();
  }
}
